# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ac47tyoOiZbE1WFsH_BzNECkoHQTMPpa
"""

# ============================================================
# Proyecto Integrador: CiberEscudo IA Alejandro
# Materia: Lógica de Programación
# Carrera: Ingeniería en Inteligencia Artificial
# Descripción:
# Sistema de evaluación de riesgos digitales en estudiantes.
# ============================================================


def mostrar_encabezado():
    print("=" * 60)
    print("             CIBERESCUDO IA ALEJANDRO")
    print(" Sistema de evaluación de riesgos digitales en estudiantes")
    print("=" * 60)


def mostrar_menu():
    print("\nMENÚ PRINCIPAL")
    print("1. Iniciar evaluación de riesgo digital")
    print("2. Ver información sobre seguridad digital")
    print("3. Ver recomendaciones generales")
    print("4. Salir")


def validar_opcion(mensaje, minimo, maximo):
    """
    Función que valida que el usuario ingrese un número dentro del rango permitido.
    """
    while True:
        try:
            opcion = int(input(mensaje))

            if minimo <= opcion <= maximo:
                return opcion
            else:
                print(f"Error: ingrese una opción entre {minimo} y {maximo}.")

        except ValueError:
            print("Error: debe ingresar un número válido.")


def obtener_preguntas():
    """
    Lista de preguntas del sistema.
    Cada pregunta tiene opciones y cada opción tiene un puntaje.
    Mientras más seguro sea el hábito digital, mayor será el puntaje.
    """
    preguntas = [
        {
            "pregunta": "¿Utilizas la misma contraseña en varias cuentas?",
            "opciones": [
                ("Sí, siempre", 1),
                ("A veces", 2),
                ("No, uso contraseñas diferentes", 3)
            ]
        },
        {
            "pregunta": "¿Verificas los enlaces antes de abrirlos?",
            "opciones": [
                ("Nunca", 1),
                ("A veces", 2),
                ("Siempre", 3)
            ]
        },
        {
            "pregunta": "¿Compartes información personal en redes sociales?",
            "opciones": [
                ("Frecuentemente", 1),
                ("A veces", 2),
                ("Casi nunca", 3)
            ]
        },
        {
            "pregunta": "¿Tienes activada la verificación en dos pasos?",
            "opciones": [
                ("No", 1),
                ("Solo en algunas cuentas", 2),
                ("Sí, en mis cuentas importantes", 3)
            ]
        },
        {
            "pregunta": "¿Descargas archivos de páginas desconocidas?",
            "opciones": [
                ("Frecuentemente", 1),
                ("A veces", 2),
                ("Nunca", 3)
            ]
        },
        {
            "pregunta": "¿Revisas los permisos de las aplicaciones?",
            "opciones": [
                ("Nunca", 1),
                ("A veces", 2),
                ("Siempre", 3)
            ]
        },
        {
            "pregunta": "¿Utilizas herramientas de inteligencia artificial sin verificar la información?",
            "opciones": [
                ("Siempre", 1),
                ("A veces", 2),
                ("Nunca, siempre verifico", 3)
            ]
        },
        {
            "pregunta": "¿Reconoces correos sospechosos o intentos de phishing?",
            "opciones": [
                ("No los reconozco", 1),
                ("A veces", 2),
                ("Sí, los identifico fácilmente", 3)
            ]
        }
    ]

    return preguntas


def realizar_evaluacion():
    """
    Función principal para realizar la evaluación del usuario.
    """
    print("\nEVALUACIÓN DE RIESGO DIGITAL")
    print("-" * 60)

    nombre = input("Ingrese su nombre: ")

    while nombre.strip() == "":
        print("El nombre no puede estar vacío.")
        nombre = input("Ingrese su nombre: ")

    preguntas = obtener_preguntas()
    puntaje_total = 0
    respuestas_usuario = []

    print(f"\nHola, {nombre}. Responde las siguientes preguntas:")
    print("Selecciona una opción del 1 al 3.\n")

    for i, item in enumerate(preguntas, start=1):
        print(f"{i}. {item['pregunta']}")

        for numero_opcion, opcion in enumerate(item["opciones"], start=1):
            texto_opcion = opcion[0]
            print(f"   {numero_opcion}. {texto_opcion}")

        respuesta = validar_opcion("Respuesta: ", 1, 3)

        texto_respuesta = item["opciones"][respuesta - 1][0]
        puntaje = item["opciones"][respuesta - 1][1]

        puntaje_total += puntaje

        respuestas_usuario.append({
            "pregunta": item["pregunta"],
            "respuesta": texto_respuesta,
            "puntaje": puntaje
        })

        print()

    nivel, interpretacion = clasificar_riesgo(puntaje_total)
    recomendacion = generar_recomendacion(nivel)

    mostrar_resultado(nombre, puntaje_total, nivel, interpretacion, recomendacion)

    guardar_reporte(nombre, puntaje_total, nivel, interpretacion, recomendacion, respuestas_usuario)


def clasificar_riesgo(puntaje):
    """
    Clasifica el riesgo digital según el puntaje obtenido.
    Puntaje mínimo: 8
    Puntaje máximo: 24
    """
    if puntaje >= 8 and puntaje <= 13:
        nivel = "Riesgo alto"
        interpretacion = "El usuario presenta hábitos digitales inseguros y necesita mejorar su protección."
    elif puntaje >= 14 and puntaje <= 19:
        nivel = "Riesgo medio"
        interpretacion = "El usuario tiene algunos hábitos seguros, pero todavía debe fortalecer su seguridad digital."
    else:
        nivel = "Riesgo bajo"
        interpretacion = "El usuario demuestra buenas prácticas de seguridad digital."

    return nivel, interpretacion


def generar_recomendacion(nivel):
    """
    Genera recomendaciones personalizadas según el nivel de riesgo.
    """
    if nivel == "Riesgo alto":
        recomendacion = (
            "Se recomienda utilizar contraseñas seguras, activar la verificación en dos pasos, "
            "evitar abrir enlaces desconocidos, no descargar archivos sospechosos y proteger la "
            "información personal en redes sociales."
        )
    elif nivel == "Riesgo medio":
        recomendacion = (
            "Se recomienda reforzar los hábitos de seguridad digital, revisar los permisos de las "
            "aplicaciones, verificar la información obtenida en internet o mediante inteligencia "
            "artificial y evitar compartir datos sensibles."
        )
    else:
        recomendacion = (
            "El usuario mantiene buenos hábitos digitales. Se recomienda continuar protegiendo sus "
            "datos, actualizar contraseñas periódicamente y mantenerse informado sobre nuevos riesgos "
            "tecnológicos."
        )

    return recomendacion


def mostrar_resultado(nombre, puntaje, nivel, interpretacion, recomendacion):
    """
    Muestra el resultado final de la evaluación.
    """
    print("=" * 60)
    print("RESULTADO DE LA EVALUACIÓN")
    print("=" * 60)
    print(f"Usuario evaluado: {nombre}")
    print(f"Puntaje obtenido: {puntaje}/24")
    print(f"Nivel de seguridad digital: {nivel}")
    print("\nInterpretación:")
    print(interpretacion)
    print("\nRecomendación personalizada:")
    print(recomendacion)
    print("=" * 60)


def guardar_reporte(nombre, puntaje, nivel, interpretacion, recomendacion, respuestas_usuario):
    """
    Guarda un reporte básico en un archivo de texto.
    Esta funcionalidad permite evidenciar mejor el resultado del sistema.
    """
    nombre_archivo = "reporte_ciberescudo.txt"

    with open(nombre_archivo, "w", encoding="utf-8") as archivo:
        archivo.write("REPORTE DE EVALUACIÓN - CIBERESCUDO IA\n")
        archivo.write("=" * 60 + "\n")
        archivo.write(f"Usuario evaluado: {nombre}\n")
        archivo.write(f"Puntaje obtenido: {puntaje}/24\n")
        archivo.write(f"Nivel de seguridad digital: {nivel}\n\n")

        archivo.write("Interpretación:\n")
        archivo.write(interpretacion + "\n\n")

        archivo.write("Recomendación personalizada:\n")
        archivo.write(recomendacion + "\n\n")

        archivo.write("Detalle de respuestas:\n")
        archivo.write("-" * 60 + "\n")

        for i, respuesta in enumerate(respuestas_usuario, start=1):
            archivo.write(f"{i}. {respuesta['pregunta']}\n")
            archivo.write(f"Respuesta: {respuesta['respuesta']}\n")
            archivo.write(f"Puntaje: {respuesta['puntaje']}\n\n")

    print(f"\nSe generó el archivo '{nombre_archivo}' con el reporte de la evaluación.")


def mostrar_informacion_seguridad():
    """
    Muestra información educativa sobre seguridad digital.
    """
    print("\nINFORMACIÓN SOBRE SEGURIDAD DIGITAL")
    print("-" * 60)
    print("La seguridad digital consiste en proteger la información personal,")
    print("las cuentas, los dispositivos y la identidad de los usuarios en internet.")
    print()
    print("Algunos riesgos digitales comunes son:")
    print("- Robo de contraseñas.")
    print("- Correos falsos o phishing.")
    print("- Descarga de archivos maliciosos.")
    print("- Exposición de datos personales.")
    print("- Uso de redes Wi-Fi inseguras.")
    print("- Desinformación generada por fuentes no verificadas.")
    print()
    print("El uso responsable de la tecnología permite reducir estos riesgos")
    print("y aprovechar mejor las herramientas digitales en la educación y la vida diaria.")


def mostrar_recomendaciones_generales():
    """
    Muestra recomendaciones generales de seguridad digital.
    """
    print("\nRECOMENDACIONES GENERALES")
    print("-" * 60)
    print("1. Utiliza contraseñas diferentes para cada cuenta.")
    print("2. Activa la verificación en dos pasos.")
    print("3. No abras enlaces sospechosos.")
    print("4. Verifica la información obtenida de internet o herramientas de IA.")
    print("5. No compartas datos personales en redes sociales.")
    print("6. Descarga archivos únicamente desde sitios confiables.")
    print("7. Revisa los permisos de las aplicaciones instaladas.")
    print("8. Mantén tus dispositivos y aplicaciones actualizados.")


def ejecutar_sistema():
    """
    Función principal que ejecuta el sistema completo.
    """
    while True:
        mostrar_encabezado()
        mostrar_menu()

        opcion = validar_opcion("\nSeleccione una opción: ", 1, 4)

        if opcion == 1:
            realizar_evaluacion()

            continuar = input("\n¿Desea volver al menú principal? (s/n): ").lower()

            if continuar != "s":
                print("\nGracias por utilizar CiberEscudo IA. ¡Hasta pronto!")
                break

        elif opcion == 2:
            mostrar_informacion_seguridad()
            input("\nPresione Enter para volver al menú principal...")

        elif opcion == 3:
            mostrar_recomendaciones_generales()
            input("\nPresione Enter para volver al menú principal...")

        elif opcion == 4:
            print("\nGracias por utilizar CiberEscudo IA. ¡Hasta pronto!")
            break


# Inicio del programa
if __name__ == "__main__":
    ejecutar_sistema()